### ISSUE TITLE
Shell command "power" not recognized

### ISSUE THREAD

**Issue by AMTQ** [fablabbcn/smartcitizen-docs#10]
Hi there!
It seems my smart cititzen kit 2.1 does not recognize the command "power" as mentioned here: 
https://docs.smartcitizen.me/Guides/getting%20started/Using%20the%20Shell/
All other commands seem to work tough. Is this command still available or has it been removed?

22:31:31.402 -> SCK > version
22:31:33.115 -> Hardware Version: 2.1
22:31:33.115 -> SAM Hardware ID: xxxxxxx
22:31:33.115 -> SAM version: 0.9.5-a91f850
22:31:33.115 -> SAM build date: 2019-08-20T13:25:01Z
22:31:33.115 -> ESP MAC address: xxxxxxx
22:31:33.115 -> ESP version: 0.9.2-a91f850
22:31:33.115 -> ESP build date: 2019-08-20T13:17:16Z
22:31:33.115 -> SCK > power
22:31:34.179 -> Unrecognized command!!
22:31:34.226 -> SCK >

**Comment by pral2a** [comment]
Hi! I will suggest you first try to upgrade your firmware to the latest version, you are running `0.9.5` on the main MCU and `0.9.2` on the Wi-Fi model, while the latest release is `0.9.7` and the latests pre-release is `0.9.8`

https://docs.smartcitizen.me/Guides/firmware/Update%20the%20firmware/

**Comment by AMTQ** [comment]
Ok. So the INFO_UF2.TXT is wrong, as it indicates model Smartcitizen Kit 2.0 instead of 2.1. The link goes also to the 2.0 instead of 2.1. But apart from this, I tried flashing the new firmware 0.9.7 and now the Power command is recognized. Thx for your help!

**Comment by pral2a** [comment]
@AMTQ great it work!

@vicobarberan could you check the issue related to INFO_UF2.TXT

Thanks!

**Comment by oscgonfer** [comment]
Seems this got solved in the latest [firmware release (0.9.8)](https://github.com/fablabbcn/smartcitizen-kit-21/releases/tag/0.9.8), reopen if not.
