### ISSUE TITLE
Link to third party sensors is wrong

### ISSUE THREAD

**Issue by AMTQ** [fablabbcn/smartcitizen-docs#12]
Hi there
On https://docs.smartcitizen.me/Components/Auxiliary%20Connector/ there is a link to the guide on how to use third party sensors. The link points to https://docs.smartcitizen.me/Guides/Third%20party%20sensors which does not exist. It should probably be https://docs.smartcitizen.me/Guides/getting%20started/Third%20party%20sensors/ instead?
edit: github does not like links with spaces...

**Comment by oscgonfer** [comment]
Thank you! Fixed in https://github.com/fablabbcn/smartcitizen-docs/commit/4f059d84a6f0ee514e630f80a01ffc4d4a318edc
