### ISSUE TITLE
Missing Link: Update the firmware.md and text issues

### ISSUE THREAD

**Issue by bryn51** [fablabbcn/smartcitizen-docs#15]
The Update firmware documentation File contains a missing Link.

The final paragraph has a link to Editing the Firmware.md file, which looks like it should be a link, but is not.

Through the text in the document there are lots of grey boxes containing informative text, and there is a horizontal scroll button.  It would be more visually appealing if <cr> was inserted at appropriate placed to eliminate the horizontal scrolling;

**Comment by oscgonfer** [comment]
Fixed link. Reopen if missing.  https://github.com/fablabbcn/smartcitizen-docs/commit/492cb7d3b15c4688bed5d5e82bd6c05cb33a153b

As for the boxes... we can't do anything.
