### ISSUE TITLE
missing Installation Instruction in 'Edit The Firmware'

### ISSUE THREAD

**Issue by bryn51** [fablabbcn/smartcitizen-docs#20]
This file contains directions on editing of the firmware; and it includes instructions for setting up of Python.

In attempting a build on Windows 10 using 'make.py'; I found that the Python installation was missing a module 'requests' that caused an error on execution of 'tools/sck.py'.

I suggest that the 'Edit The Firmware' document should include an instruction to install the missing module using the command '>python -m pip install requests

**Comment by bryn51** [comment]
'Edit The Firmware' document should include an instruction to install the missing module using the command '>python -m pip install requests

**Comment by oscgonfer** [comment]
Closed now after update, thanks!
