### ISSUE TITLE
smartcitizen-docs/docs/Guides/firmware/Edit the Firmware.md : paltformio instructions need expansion

### ISSUE THREAD

**Issue by bryn51** [fablabbcn/smartcitizen-docs#21]
The guide indicates that only the CLI version of platformio is required.  That's a bit brief and misleading.  You will also need something to edit the code.
Thusly; something like the following needs to be added to the document.:
If you have windows, only the GUI version (vscode) is available; but it has the CLI version available via PowerShell. An environment variable (PATH) needs to be set to give access to pio.exe.  Its given in the Platformio instructions.

If Platformio GUI is used to edit code, it will be tempting to use the 'terminal' button to compile the code; which executes windows PowerShell.  However PowerShell executed this way does not inherit the windows user environment settings, and the PIO command will not be found.
Thus, its necessary to user PowerShell executed from Windows to compile the code (and to publish it onto the USB port into Firmware).

**Comment by oscgonfer** [comment]
For compiling the firmware, one doesn't need to install the GUI, only the CLI. The platformio instructions are constantly changing, so we rather leave a link to platformio's official docs.

Surely, you need something to edit the code, but that we assumed is by default understood if you want to edit the files. Anyone can use any editor for it, no requirements as long as it's not [bad](https://www.quora.com/In-your-opinion-what-is-the-worst-text-editor-for-programming?share=1)

I added your comments to the docs. Hope it helps!

**Comment by oscgonfer** [comment]
https://github.com/fablabbcn/smartcitizen-docs/commit/1c0735bae126211d5b28827d3807a03b6420fc73
