### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by antoinestudio** [fablabbcn/smartcitizen-docs#8]
Broken link on [this page](https://docs.smartcitizen.me/Components/Auxiliary%20Connector/#soil-and-water):
> Check the [Soil and water measurements](https://docs.smartcitizen.me/Soil%20and%20water/) documentation with examples on sensors such as:

`404 - Not found`

**Comment by oscgonfer** [comment]
Fixed via https://github.com/fablabbcn/smartcitizen-docs/commit/474331be3a4e368a90f851bcc6e1cd4e391615fb
